version : '3'
services:
    web:
        image: python:3
        restart: always
        ports: 
            - '5000:5000'

    create:
        image: gunicorncreate

    show:
        image: gunicornshow
        
    
    

    