version: '3.6'

services:
  api:
    build: .
    depends_on:
      - db
    ports: 
      - 5000:5000
    volumes:
      - .:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    restart: always

  db:
    image: postgres:9.6-alpine
    container_name: db
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports: 
      - 5405:5432
    restart: always
    volumes:
      - .:/usr/src/app/app
      - ./pgdata:/usr/src/app/pgdata
    

